app/src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_NICKNAME', fields: ['nickname'])]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['nickname'], message: 'Ce pseudo est déjà utilisé')]
#[UniqueEntity(fields: ['email'], message: 'Un compte existe déjà avec cette adresse email')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $nickname = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $isVerified = false;

    /**
     * @var Collection<int, Posts>
     */
    #[ORM\OneToMany(targetEntity: Posts::class, mappedBy: 'users', orphanRemoval: true)]
    private Collection $posts;

    /**
     * @var Collection<int, Comments>
     */
    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'users', orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): static
    {
        $this->nickname = $nickname;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->nickname;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function isVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Posts>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Posts $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setUsers($this);
        }

        return $this;
    }

    public function removePost(Posts $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUsers() === $this) {
                $post->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUsers($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUsers() === $this) {
                $comment->setUsers(null);
            }
        }

        return $this;
    }
}

app/src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Form\RequestResetPasswordForm;
use App\Form\ResetPasswordForm;
use App\Repository\UsersRepository;
use App\Service\JWTService;
use App\Service\SendEmailService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        
        // if ($this->getUser()){
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route(path: '/mot-de-passe-oublie', name: 'app_request_forgotten_password')]
    public function forgottenPassword(Request $request, UsersRepository $usersRepository, JWTService $jwt, SendEmailService $mail):Response
    {
        $form = $this->createForm(RequestResetPasswordForm::class);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            // Formulaire envoyé
            // Recup User
            $user = $usersRepository->findOneByEmail($form->get('email')->getData());
            // Verif si user
            if($user){
                // User existe
                // Creation du Token
                // --- Header
                $header = [
                    'typ'=>'JWT',
                    'alg'=>'HS256'
                ];
                // --- Payload
                $payload = [
                    'user_id'=>$user->getId()
                ];
                // --- Generation
                $token = $jwt->generate($header, $payload, $this->getParameter('app.jwtsecret'));
                // dd($token);

                // Génération de l'URL vers app_reset_password
                $url = $this->generateUrl('app_reset_password', ['token' => $token], UrlGeneratorInterface::ABSOLUTE_URL);

                //Envoyer l'e-mail
                $mail->send(
                    'no-reply@openblog.fr',
                    $user->getEmail(),
                    'Récupération de votre mot de passe sur le site OpenBlog',
                    'reset_password',
                    compact('user', 'url')
                );

                $this->addFlash('success', 'Email envoyé avec succès');
                return $this->redirectToRoute('app_login'); 

            }
            // $user null
            $this->addFlash('danger', 'Un problème est survenu');
            return $this->redirectToRoute('app_login'); 
        }

        return $this->render('security/request_reset_password.html.twig', [
            'requestPassForm' => $form->createView()
        ]);
    }

    #[Route(path: '/mot-de-passe-oublie/{token}', name: 'app_reset_password')]
    public function resetPassword($token, JWTService $jwt, UsersRepository $usersRepository, Request $request, UserPasswordHasherInterface $passwordHasher, EntityManagerInterface $em): Response
    {
        // Verif validité (cohérent/expiration/signature)
        if($jwt->isValid($token) && !$jwt->isExpired($token) && $jwt->check($token, $this->getParameter('app.jwtsecret'))){
            //token valide recup données (payload)
            $payload = $jwt->getPayload($token);
            // dd($payload);

            //On recup le user
            $user = $usersRepository->find($payload['user_id']);

            if($user){
                $form = $this->createForm(ResetPasswordForm::class);
                
                $form->handleRequest($request);

                if($form->isSubmitted() && $form->isValid()) {
                    $user->setPassword($passwordHasher->hashPassword($user, $form->get('password')->getData()));

                    $em->flush();

                    $this->addFlash('success', 'Mot de passe modifé avec succès');
                    return $this->redirectToRoute('app_login');
                }

                return $this->render('security/reset_password.html.twig', [
                    'passForm' => $form->createView()
                ]);
            }
        }
        $this->addFlash('danger', 'Le token est invalide ou a expiré');
        return $this->redirectToRoute('app_login');
    }

}

app/templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Me Connecter{% endblock %}

{% block body %}
    <form method="post">
        {% if error %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}

        {% if app.user %}
            <div class="mb-3">
                Vous êtes connecté(e) en tant que {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Me déconnecter</a>
            </div>
        {% endif %}

        <h1 class="h3 mb-3 font-weight-normal">Me connecter</h1>

        <div>
            <label for="username">Pseudo</label>
            <input type="text" value="{{ last_username }}" name="_username" id="username" class="form-control" autocomplete="username" required autofocus>
        </div>

        <div>
            <label for="password">Mot de passe</label>
            <input type="password" name="_password" id="password" class="form-control" autocomplete="current-password" required>
        </div>

        <input type="hidden" name="_csrf_token" data-controller="csrf-protection" value="{{ csrf_token('authenticate') }}">

        
        {# Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html #}

        <div class="checkbox mb-3">
            <input type="checkbox" name="_remember_me" id="_remember_me">
            <label for="_remember_me">Se souvenir de moi</label>
        </div>
       

        <button class="btn btn-lg btn-primary" type="submit">
            Connexion
        </button>

        <p><a href="{{ path('app_request_forgotten_password') }}">Mot de passe oublié</a></p>
        <p>Pas encore inscrit(e) ? <a href="{{ path('app_register') }}">M'inscrire</a></p>

    </form>
{% endblock %}

app/templates/security/request_reset_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rénitialiser mon mot de passe{% endblock %}

{% block body %}
    <section>
        <h1>Rénitialiser mon mot de passe</h1>
        {{ form_start(requestPassForm) }}
            {{ form_row(requestPassForm.email, {
                label: 'Email'
            }) }}
            <button type="submit">Envoyer</button>
        {{ form_end(requestPassForm) }}
    </section>
{% endblock %}

app/templates/security/reset_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rénitialiser mon mot de passe{% endblock %}

{% block body %}
    <section>
        <h1>Rénitialiser mon mot de passe</h1>
        {{ form_start(passForm) }}
            {{ form_row(passForm.password, {
                label: 'Mot de passe'
            }) }}
            <button type="submit">Modifier</button>
        {{ form_end(passForm) }}
    </section>
{% endblock %}